name: Releases

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          check-latest: true

      - name: Gradle Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleRelease
          gradle-home-cache-cleanup: true

      - name: Uploading Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-normal-release-unsigned.apk
          path: ./app/build/outputs/apk/normal/release/app-normal-release-unsigned.apk
          if-no-files-found: error

      - name: Uploading Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-play-release-unsigned.apk
          path: ./app/build/outputs/apk/play/release/app-play-release-unsigned.apk
          if-no-files-found: error

      - name: Releases
        uses: softprops/action-gh-release@v1
        with:
          body: Bump Version
          files: |
            ./app/build/outputs/apk/normal/release/app-normal-release-unsigned.apk
            ./app/build/outputs/apk/play/release/app-play-release-unsigned.apk
